# Generated by Django 4.2.7 on 2025-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[("C++", "C++"), ("Python", "Python")],
                max_length=20,
                verbose_name="编程语言",
            ),
        ),
    ]
