# Generated by Django 4.2.7 on 2025-10-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=500, verbose_name="个人简介"),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=100, verbose_name="学校"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "total_submissions",
                    models.IntegerField(default=0, verbose_name="总提交数"),
                ),
                (
                    "accepted_submissions",
                    models.IntegerField(default=0, verbose_name="通过提交数"),
                ),
                ("total_solved", models.IntegerField(default=0, verbose_name="解决题目数")),
                ("easy_solved", models.IntegerField(default=0, verbose_name="简单题通过数")),
                (
                    "medium_solved",
                    models.IntegerField(default=0, verbose_name="中等题通过数"),
                ),
                ("hard_solved", models.IntegerField(default=0, verbose_name="困难题通过数")),
                ("rating", models.IntegerField(default=1500, verbose_name="积分")),
                ("rank", models.IntegerField(default=0, verbose_name="排名")),
                ("github", models.URLField(blank=True, verbose_name="GitHub")),
                ("blog", models.URLField(blank=True, verbose_name="个人博客")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
                "ordering": ["-rating", "-total_solved"],
            },
        ),
    ]
