# Generated by Django 4.2.7 on 2025-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                choices=[("C++", "C++"), ("Python", "Python"), ("Both", "两者都喜欢")],
                default="Both",
                max_length=20,
                verbose_name="编程语言偏好",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="手机号"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "浅色主题"), ("dark", "深色主题"), ("auto", "跟随系统")],
                default="auto",
                max_length=20,
                verbose_name="主题偏好",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="wechat",
            field=models.CharField(blank=True, max_length=50, verbose_name="微信号"),
        ),
    ]
